export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  SUPER_ADMIN: 'SUPER_ADMIN',
  CHEF: 'CHEF',
  BAKER: 'BAKER',
  FLORIST: 'FLORIST',
  HAMPER_DESIGNER: 'HAMPER_DESIGNER',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER'
};