import express from "express";
import crypto from "crypto";
import Order from "../models/order.js";
import Activity from "../models/activity.js";
import Product from "../models/product.js";
import mongoose from "mongoose";

const router = express.Router();

// Shared Idempotent Payment Processor
const processSuccessfulPayment = async (rzpOrderId, rzpPaymentId) => {
  const session = await mongoose.startSession();
  session.startTransaction();
  try {
    const order = await Order.findOne({ "paymentResult.id": rzpOrderId }).session(session);
    
    // Prevent duplicate processing
    if (!order || order.isPaid) {
      await session.abortTransaction();
      return; 
    }

    // Atomic stock deduction for each item in the order
    // Assuming orderItems contains product IDs that reference the Product model
    for (const item of order.orderItems) {
      if (item.product) {
        // We only decrement stock if the product exists and has enough stock
        await Product.findOneAndUpdate(
          { _id: item.product, stock: { $gte: item.qty } },
          { $inc: { stock: -item.qty } },
          { session }
        );
      }
    }

    // Update order status
    order.isPaid = true;
    order.paidAt = Date.now();
    order.paymentResult = {
      ...order.paymentResult,
      status: "SUCCESS",
      id: rzpPaymentId
    };
    
    await order.save({ session });
    
    // Create activity log
    await Activity.create([{
      user: order.user,
      type: 'order',
      action: 'Payment Verified via Webhook',
      details: `Order ID: ${order._id}, Payment ID: ${rzpPaymentId}`
    }], { session });

    await session.commitTransaction();
  } catch (error) {
    await session.abortTransaction();
    console.error("Critical failure during webhook payment processing:", error);
  } finally {
    session.endSession();
  }
};

// @desc    Handle Razorpay Webhooks
// @route   POST /api/webhook/razorpay
// @access  Public
// Note: This route must use express.raw({type: 'application/json'}) in server.js
router.post("/razorpay", async (req, res) => {
  try {
    const secret = process.env.RAZORPAY_WEBHOOK_SECRET;
    
    if (!secret) {
      console.warn("Webhook secret not configured");
      return res.status(200).send("OK");
    }

    // signature generated by razorpay
    const signature = req.headers["x-razorpay-signature"];

    // validate signature
    const expectedSignature = crypto
      .createHmac("sha256", secret)
      .update(req.body) // req.body must be raw string here
      .digest("hex");

    if (signature !== expectedSignature) {
      return res.status(400).send("Invalid Signature");
    }

    // parse body safely
    const payload = JSON.parse(req.body);
    const event = payload.event;

    if (event === "payment.captured") {
      const paymentEntity = payload.payload.payment.entity;
      await processSuccessfulPayment(paymentEntity.order_id, paymentEntity.id);
    }

    res.status(200).send("OK");
  } catch (error) {
    console.error("Webhook Error:", error.message);
    res.status(500).send("Server Error");
  }
});

export default router;
